apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-kc33
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0072-tenant/tkrw-pr712-0075-0072-app/devfile-sample-kc33@sha256:cec655268ad03b197ff2df2c84fcaab9935889102e7aa55697840d09aa36da7a
        name: my-nodejs
        resources: {}
status: {}
